### ISSUE TITLE
Issue #5: User wants to see their location on google maps

### ISSUE THREAD

**Issue by ChrisGitmed** [ninajhun/graphQL-hackathon#5]
### 💰 Feature
User wants to see their location on google maps.

### 🗒️ Notes
This will require me to query the google maps api for the current location. And then neatly display said info.
### 🖼 Wireframe
<img width="259" alt="Screen Shot 2021-04-20 at 3 34 47 PM" src="https://user-images.githubusercontent.com/71002706/115472087-f3878c80-a1ed-11eb-9bd9-89065dc69438.png">

### ✅ Tasks
- [x] Create a widget for the Google Map.
- [x] Make sure the widget has proper styling (layout spacing).
- [x] Add the title. (I see you...)
- [x] Create a function which calls the Google Maps API and returns a location.
- [x] Tweak the function to use the clients IP address and return THAT location.
- [x] Tweak the widget to display this information.
- [x] Test, polish, KILL ALL BUGS.
